Fixing Typing Errors
ErikSchierboom/knockout-paging pull request #20
Opened 2017-05-18 13:28 UTC by amragaey

Referring to #19 
This is the proposed solution.

2017-05-18 19:19 UTC, ErikSchierboom requested changes
First of all, thanks for reporting the issue and even submitting a PR to fix it! I have one request: instead of commenting the unnecessary lines, could you remove them?

2017-05-19 22:59 UTC, amragaey commented
I removed the unnecessary lines, hope you could merge now peacefully.

Thanks!

2017-05-20 08:40 UTC, ErikSchierboom requested changes

2017-05-20 08:40 UTC, ErikSchierboom commented on dist/knockout.d.ts
> +    // [key: string]: KnockoutBindingHandler;
Could you perhaps also remove this comment?

2017-05-20 20:33 UTC, amragaey commented
Thanks for your attention, check now!

2017-05-20 20:46 UTC, ErikSchierboom approved these changes
Great work! Thanks. :tada:

2017-05-20 20:46 UTC, merged